### ISSUE TITLE
Disable shading

### ISSUE THREAD

**Issue by renmengye** [ShapeNet/shapenet-viewer#10]
Hi,

Thank you for your great contribution of releasing ShapeNet and an amazing viewer. I am wondering if I can disable shading entirely, and just look at the color of the object from all view angles. I tried a few settings of the MTL file, but I can only get shader-free image from the intial camera angle. Could you point me where I should change in the code to make it happen?

Thanks a lot!

Mengye Ren

**Comment by msavva** [comment]
You can get  unshaded materials (i.e. flat colors) by setting the illumination mode appropriately in your MTL file.  Specifying `illum 0` for each material you want to be unshaded, should result in flat shading of that material.  Please refer to the documentation of the MTL `illum` directive at http://paulbourke.net/dataformats/mtl/
