### ISSUE TITLE
change the save path of renderings

### ISSUE THREAD

**Issue by suhaochina** [ShapeNet/shapenet-viewer#11]
When I load a model from a specified path (e.g, /a/b/c/d.kmz) and conduct off-line rendering, I find it difficult to save the screenshots. The generated output path will be: $WORK_DIR/a/b/c/d.kmz/a/b/c/d.kmz-1.png. The system returns java.io.FileNotFoundException for not being able to save to path.

Is it possible manually specify the output folder for the renderings?

**Comment by msavva** [comment]
Error was due to a bug in saving screenshots for locally loaded models, and is fixed by commit c03bb56b18b13c35cbe3351103ba9188e6300de7.

Also, the new command `set modelScreenshotDir <path>` allows for manual setting of screenshot output base directory.
