### ISSUE TITLE
Cannot operate register.

### ISSUE THREAD

**Issue by kealennieh** [ShapeNet/shapenet-viewer#12]
Hello,
    After I run ./scripts/viewer.sh  successfully, I press F4 into console pattern. However, I cannot operate register successfully. I input "register shapeNetCore /home/kealen/ShapeNetCore", since I load and extract ShapeNetCore from ShapeNet website into this folder. I cannot find out where the trouble is. How can I fix this problem ? Thanks a lot !

**Comment by msavva** [comment]
Apologies for the long delay.  Can you please provide a copy of the error output that is printed to the console when you attempt to register the data?  Most likely the local directory to which you have extracted the ShapeNetCore data does not contain a taxonomy.json file.  This file is part of the main ShapeNetCore.v1 zip archive and needs to be present in the root of the local directory.  Note that if you are using the updated geometry from the v2 release, you will still need the taxonomy.json file from the v1 release (this file has not changed between the releases).

**Comment by fgolemo** [comment]
The problem is that the ShapeNetCore.v2 download doesn't contain the taxonomy.json file. Where can we find it?
I got the same error and the Java Exception is 
`java.io.FileNotFoundException: /path-to-my-unzipped-shapenetcore.v2/taxonomy.json (No such file or directory)`

**Comment by fgolemo** [comment]
Oh and in the original ShapeNetCore.v1 README it says that the taxonomy.json was obtained from

http://shapenet.cs.stanford.edu/resources/data/shapenetcore.taxonomy.json

...but this URL doesn't seem to be valid anymore

**Comment by msavva** [comment]
Apologies for the confusion. The URL was out-of-date in the README file.  The correct URL is https://www.shapenet.org/resources/data/shapenetcore.taxonomy.json . It has now been updated in the README, and the taxonomy.json file is also now included in the ShapeNetCore.v2.zip archive.

**Comment by ashimdahal** [comment]
is the website down agaim @msavva ?

**Comment by YufengJin** [comment]
@msavva 
I downloaded the ShapeNetCore.v2 dataset via Huggingface, but it does not include the taxonomy.json file. The official website link appears to be broken, and I couldn't find the taxonomy file online. The links you provided are also inaccessible.

Are you still actively maintaining the ShapeNet dataset?


> Apologies for the confusion. The URL was out-of-date in the README file. The correct URL is https://www.shapenet.org/resources/data/shapenetcore.taxonomy.json . It has now been updated in the README, and the taxonomy.json file is also now included in the ShapeNetCore.v2.zip archive.

**Comment by shngt** [comment]
Found the taxonomy.json using the Wayback Machine - might be out of date, but leaving this here in case useful to others.

[shapenet_taxonomy.json](https://github.com/user-attachments/files/26060825/shapenet_taxonomy.json)
