### ISSUE TITLE
"make" gets error

### ISSUE THREAD

**Issue by ywpkwon** [ShapeNet/shapenet-viewer#14]
When I do `make`, I got error like 
```
>> make
bin/sbt package
Unrecognized VM option 'MaxPermSize=256M'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Makefile:32: recipe for target 'package' failed
make: *** [package] Error 1
```

For information, I am using Ubuntu 16.04 and
```
>> java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
```

**Comment by msavva** [comment]
Please install the official Oracle JDK instead of the OpenJDK.

**Comment by ywpkwon** [comment]
Thanks! It helped me a lot.

For those who may have same questions: I followed this link. https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04
See `Installing the Oracle JDK` section.
