### ISSUE TITLE
Unable to access jarfile...

### ISSUE THREAD

**Issue by viggyr** [ShapeNet/shapenet-viewer#17]
Error: Unable to access jarfile ./../target/scala-2.11//shapenet-viewer-assembly-0.1.0.jar

I get this error when i run viewer.sh
Please help me sort this one out

**Comment by msavva** [comment]
Please check that make has successfully compiled the code.  After successful compilation, the quoted jar file should exist in `target/scala-2.11/`
Then, you should be able to run by invoking `scripts/viewer.sh` from the root directory of the repository.
