### ISSUE TITLE
Unable to download shapenetcore dataset

### ISSUE THREAD

**Issue by viggyr** [ShapeNet/shapenet-viewer#19]
I got access to the shapenetcore dataset a week back and due to poor internet connection, it got cancelled a few times and i kept trying. Since  yesterday though when i click on download on the page, it is not responding. Its showing ERR_CONNECTION_RESET. Please help me sort this one out.

**Comment by msavva** [comment]
Our data server was offline due to a power outage.  Please try to download again, and let us know if you still experience issues.

**Comment by viggyr** [comment]
Its working now. Thanks a lot
