### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by xiaopengguo1406** [ShapeNet/shapenet-viewer#20]
I try install the shapenet-viewer on ubuntu16.04.However,when I run the make, the error happens:
unresolved dependency: org.scala-sbt#sbt;0.13.7: not found
Error during sbt execution: Error retrieving required libraries
  (see /home/xiaopengguo/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 0.13.7
Makefile:32: recipe for target 'package' failed
make: *** [package] Error 1
What's the problem with it,thank you very much!

**Comment by msavva** [comment]
This looks a dependency download error. The most likely cause is that the machine where you are installing is behind a proxy which interferes with connections to the dependency servers.

Do you see any successful download messages for `.jar` files before this error is printed?  The first successful download should be https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.7/jars/sbt.jar .  Can you provide a full log of the output of the make command?

**Comment by xiaopengguo1406** [comment]
Thank you very much! I have installed the software successfully. Besides,as an appreciation, I have some suggestions for this project. 
      Firstly, I think the Compiling procedure could be more detailed.For instance, how to install java JDK1.8? a link https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04 I think is necessary. What's more, not everyone is familiar with Ubuntu. How to "ensure that following commands are in your path:java,make,wget" is also necessary in my view. 
     Secondly, I think the developer can write a small toturial about the using of this visualization software. How to set the WORK_DIR and SHAPENET_VIEWER_DIR not depicted clearly in my opinion.   
   I hope the suggestions can improve the software and I think if the readme.md becomes more detailed, the stars will have a enormous increasement in the near future.

**Comment by msavva** [comment]
Thank you for your suggestions and feedback.  We are currently going through a survey process on usage of the ShapeNet tools, and will also work on improving documentation in the near future.
