### ISSUE TITLE
How/Why do certain objects render correctly in the ShapeNet Viewer but not in Blender?

### ISSUE THREAD

**Issue by airalcorn2** [ShapeNet/shapenet-viewer#28]
As discussed on [the ShapeNet forums](https://www.shapenet.org/qaforum/index.php?qa=19&qa_1=does-anyone-else-find-that-models-load-incorrectly-blender), some objects do not render correctly in Blender. For example, the object found at `ShapeNetCore/02958343/114b662c64caba81bb07f8c2248e54bc` (a "NYPD Highway Patrol Dodge Charger") looks like this in Blender:

![blender_car](https://user-images.githubusercontent.com/1927770/54497980-2a806b00-48cf-11e9-8739-23715a968f93.png)

but, in the [ShapeNet viewer](https://github.com/ShapeNet/shapenet-viewer), it looks like this:

![car_shapenet](https://user-images.githubusercontent.com/1927770/54497983-2f451f00-48cf-11e9-962e-3bb6346baeea.png)

As was mentioned in the forum post, the models that do not render properly in Blender seem to have a "bad topology", e.g., they include "two-sided" faces and "flipped" faces (as mentioned in the [ShapeNet Mitsuba fork](https://github.com/shi-jian/mitsuba-shapenet)). So, my question is, **HOW** does the ShapeNet Viewer/jMonkeyEngine properly render these objects? I would like to be able to replicate its process so that I can use the models with [my own rendering framework](https://github.com/airalcorn2/strike-with-a-pose).

**Comment by airalcorn2** [comment]
It looks like I fixed the issue by [adding back-face culling](https://github.com/airalcorn2/strike-with-a-pose/commit/64b1b0dc3f3699b781ac263ba38ea69fd4a972b2). Here is the car with back-face culling off:

![no_cull](https://user-images.githubusercontent.com/1927770/54501252-30d40e80-48f2-11e9-99b6-096e348cbfd1.png)

and with back-face culling on:

![with_cull](https://user-images.githubusercontent.com/1927770/54501253-36315900-48f2-11e9-859f-3ea76a732593.png)

It still looks weird in Blender, though:

![blender_car_cull](https://user-images.githubusercontent.com/1927770/54501093-2a916280-48f1-11e9-9057-9e65166d09da.png).

Here is model `ShapeNetCore/02958343/8577f3f82d5ce3ecc2fe329dd557eb52` with back-face culling off:

![no_cull_2](https://user-images.githubusercontent.com/1927770/54501451-5c0b2d80-48f3-11e9-891b-5d9c4dad8d87.png)

and with back-face culling on:

![with_cull_2](https://user-images.githubusercontent.com/1927770/54501448-5877a680-48f3-11e9-8e52-4b7f441f89a3.png)

**Comment by YuDeng** [comment]
@airalcorn2. Hi, I wonder if you have figured out how to render those shapes correctly using Blender? I encounter with the same issue but don't know how to solve it. I only have little experience about Blender.

**Comment by airalcorn2** [comment]
@YuDeng - I did not, sorry.
