### ISSUE TITLE
"unresolved dependencies" (jme3)

### ISSUE THREAD

**Issue by suhangpro** [ShapeNet/shapenet-viewer#6]
Are there any other dependencies that need to be installed before 'make' other than jdk 1.8? I got error information about unresolved dependencies about things related to jme3: 

> sbt.ResolveException: unresolved dependency: com.jme3#jme3-core;3.0.10: not found
> unresolved dependency: com.jme3#jme3-plugins;3.0.10: not found
> unresolved dependency: com.jme3#jme3-effects;3.0.10: not found
> unresolved dependency: com.jme3#jme3-jbullet;3.0.10: not found
> unresolved dependency: com.jme3#jme3-niftygui;3.0.10: not found
> unresolved dependency: com.jme3#jme3-desktop;3.0.10: not found
> unresolved dependency: com.jme3#jme3-lwjgl;3.0.10: not found
> 	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:278)
> 	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:175)
> 	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:157)
> 	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
> 	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
> 	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:128)
> 	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
> 	at sbt.IvySbt$$anon$4.call(Ivy.scala:64)
> 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
> 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
> 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
> 	at xsbt.boot.Using$.withResource(Using.scala:10)
> 	at xsbt.boot.Using$.apply(Using.scala:9)
> 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
> 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
> 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
> 	at xsbt.boot.Locks$.apply(Locks.scala:28)
> 	at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
> 	at sbt.IvySbt.withIvy(Ivy.scala:123)
> 	at sbt.IvySbt.withIvy(Ivy.scala:120)
> 	at sbt.IvySbt$Module.withModule(Ivy.scala:151)
> 	at sbt.IvyActions$.updateEither(IvyActions.scala:157)
> 	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1318)
> 	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1315)
> 	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1345)
> 	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1343)
> 	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
> 	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1348)
> 	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1342)
> 	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
> 	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1360)
> 	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1300)
> 	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1275)
> 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
> 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
> 	at sbt.std.Transform$$anon$4.work(System.scala:63)
> 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
> 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
> 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
> 	at sbt.Execute.work(Execute.scala:235)
> 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
> 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
> 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
> 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> [error] (*:update) sbt.ResolveException: unresolved dependency: com.jme3#jme3-core;3.0.10: not found
> [error] unresolved dependency: com.jme3#jme3-plugins;3.0.10: not found
> [error] unresolved dependency: com.jme3#jme3-effects;3.0.10: not found
> [error] unresolved dependency: com.jme3#jme3-jbullet;3.0.10: not found
> [error] unresolved dependency: com.jme3#jme3-niftygui;3.0.10: not found
> [error] unresolved dependency: com.jme3#jme3-desktop;3.0.10: not found
> [error] unresolved dependency: com.jme3#jme3-lwjgl;3.0.10: not found
> [error] Total time: 26 s, completed Jun 9, 2016 9:04:48 AM

I got this problem on Ubuntu 14.04 and 16.06 both with openjdk 1.8.

**Comment by msavva** [comment]
This appears to be because http://updates.jmonkeyengine.org/maven/com/jme3/jme3-desktop/3.0.10/jme3-desktop-3.0.10.pom is offline.

The build process requires downloading jMonkeyEngine as it is one of the main dependencies.  We will look into alternative sources for this dependency.

In the meantime, here is a precompiled shapenet-viewer jar file: http://dovahkiin.stanford.edu/etherion/data/shapenet/shapenet-viewer-assembly-0.1.0.jar
You can place this within the shapenet-viewer directory in target/scala-2.11/shapenet-viewer-assembly-0.1.0.jar and the viewer scripts should work.

**Comment by angelxuanchang** [comment]
Fixed by updating to jme3.1-beta and switching maven repository.

**Comment by PhilAndrew** [comment]
Hi, I notice your using jme3.1-beta, do you know of any way to get a newer version of jme3 from with a Scala sbt build?

I am using the same jme3.1-beta repo as you but I would like to move on to the newer version of jme3 within my Scala application.

**Comment by angelxuanchang** [comment]
If you want to use a newer version of jme3.1, you should be able to make a `lib/` directory and put the jme jars you build in there.  They should be automatically picked up by sbt.  See http://www.scala-sbt.org/0.13/docs/Library-Dependencies.html for more about using unmanaged dependencies with sbt.

**Comment by PhilAndrew** [comment]
Thanks for the information!

**Comment by luojiapeng14** [comment]
> 
> 
> This appears to be because http://updates.jmonkeyengine.org/maven/com/jme3/jme3-desktop/3.0.10/jme3-desktop-3.0.10.pom is offline.
> 
> The build process requires downloading jMonkeyEngine as it is one of the main dependencies. We will look into alternative sources for this dependency.
> 
> In the meantime, here is a precompiled shapenet-viewer jar file: http://dovahkiin.stanford.edu/etherion/data/shapenet/shapenet-viewer-assembly-0.1.0.jar
> You can place this within the shapenet-viewer directory in target/scala-2.11/shapenet-viewer-assembly-0.1.0.jar and the viewer scripts should work.

the precompiled link seems break downs. Is there any other way to download it?
I think it is neccessary to add the link to readme, the precompiled jar file would be very helpful.
