### ISSUE TITLE
Two shapes in Shapenet do not have vertices

### ISSUE THREAD

**Issue by daerduoCarey** [ShapeNet/shapenet-viewer#7]
I'm now doing research with Shapenet and found that the following two shapes
/ShapeNetCore.v1/03624134/67ada28ebc79cc75a056f196c127ed77
/ShapeNetCore.v1/04090263/4a32519f44dc84aabafe26e2eb69ebf4
do not have vertices or faces at all.

Can someone please help me to check this issue?

Thank you.

**Comment by msavva** [comment]
These models and some others were not correctly converted into OBJ format from the source model format in the original ShapeNetCore.v1 release.  A recent update resolves this issue and some other conversion issues relating to missing textures.  Please register for an account at our new website: https://shapenet.org and you will then be able to get download links to the updated model data.
