### ISSUE TITLE
save all screenshots not working

### ISSUE THREAD

**Issue by yzp12** [ShapeNet/shapenet-viewer#9]
Hi!
I was trying to save all screenshots for all models in chair class. 
I ran the command: save model screenshots all 3dw chair, but with no response. Any help will be appreciated!

**Comment by msavva** [comment]
Apologies for the long delay in responding.

Before running this command, you need to successfully register your local copy of ShapeNetCore using:
`register shapeNetCore <path>`
The `<path>` points to the root of an unzipped ShapeNetCore.v1 or ShapeNetCore.v2 archive containing the `taxonomy.json` file and numeric synset id subdirectories with model OBJ+MTL files.

If you are still having issues running the command, please let us know and we will re-open this issue for debugging.
